# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/box2d/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/box2d/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FetchContent.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/WriteBasicConfigVersionFile.cmake))

/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet -B/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild
