# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_ttf/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_ttf/cmake/PrivateSdlFunctions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/SelectLibraryConfigurations.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/WriteBasicConfigVersionFile.cmake))

/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet -B/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild
