# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_image/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_image/cmake/Findwebp.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_image/cmake/PrivateSdlFunctions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/libavif/libavif-config-release.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/libavif/libavif-config-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/libavif/libavif-config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindTIFF.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/SelectLibraryConfigurations.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/WriteBasicConfigVersionFile.cmake))

/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet -B/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild
