#!/usr/bin/env bash
# Install a git pre-commit hook that runs `make verify-all` before every
# commit.
#
# The hook runs the same fast local gates CI runs (check-games,
# check-examples, check-layout) - each mirrors a CMake configure-time guard
# but needs no build or configure, so the whole check takes well under a
# second. A commit that breaks any gate is blocked with a full diagnosis;
# bypass once with `git commit --no-verify`.
#
# Idempotent: re-running overwrites our own hook cleanly. A pre-existing
# hook that is not ours is backed up to .git/hooks/pre-commit.bak before
# being replaced (nothing is silently discarded).
#
# bash 3.2 compatible (macOS default bash).
#
# Usage: tools/install-hooks.sh
# Uninstall: rm .git/hooks/pre-commit

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_DIR="$ROOT/.git/hooks"
HOOK="$HOOK_DIR/pre-commit"

if [ ! -d "$ROOT/.git" ]; then
    echo "::error::no .git directory at $ROOT - run this from a git checkout" >&2
    exit 1
fi

mkdir -p "$HOOK_DIR"

if [ -e "$HOOK" ] && ! grep -q "Generated by tools/install-hooks.sh" "$HOOK" 2>/dev/null; then
    cp "$HOOK" "$HOOK.bak"
    echo "Existing pre-commit hook backed up to $HOOK.bak (it was not created by this installer)."
fi

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh - do not edit. Re-run the installer to
# refresh, or delete this file to uninstall.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if ! make verify-all; then
    echo "Commit blocked: pre-commit gates failed (see errors above)." >&2
    echo "Fix the failures, or bypass once with: git commit --no-verify" >&2
    exit 1
fi
HOOK_EOF

chmod +x "$HOOK"
echo "Installed pre-commit hook at $HOOK (runs 'make verify-all')."
echo "Uninstall: rm $HOOK   |   Bypass once: git commit --no-verify"
