# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_mixer/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_mixer/cmake/FindOpusFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_mixer/cmake/Findwavpack.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_mixer/cmake/PkgConfigHelper.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/abhishekshivakumar/gamedev/shadow/Engine/dependencies/SDL_mixer/cmake/PrivateSdlFunctions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/fluidsynth/FluidSynthConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/fluidsynth/FluidSynthConfigVersion.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/fluidsynth/FluidSynthTargets-release.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/fluidsynth/FluidSynthTargets.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/libxmp/libxmp-config-version.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/lib/cmake/libxmp/libxmp-config.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/CheckSymbolExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/local/share/cmake-3.24/Modules/WriteBasicConfigVersionFile.cmake))

/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet -B/Users/abhishekshivakumar/gamedev/shadow/Example/SpriteSheet/xbuild
